-- Users Table
CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORDHASH VARCHAR(255),
    APIKEY VARCHAR(64) UNIQUE,
    PLAN VARCHAR(20) DEFAULT 'free'
);

-- ShortCodes Table (for centralized shortcode management)
CREATE TABLE SHORTCODES (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(10) UNIQUE NOT NULL,
    STRATEGY VARCHAR(20) DEFAULT 'RANDOM', -- RANDOM, CUSTOM, USER_PREFERENCE
    USERID BIGINT REFERENCES USERS(ID),
    PREFERENCE_ORDER INTEGER,
    ISACTIVE BOOLEAN DEFAULT TRUE,
    CREATEDAT TIMESTAMP DEFAULT NOW(),
    UPDATEDAT TIMESTAMP
);

-- Urls Table
CREATE TABLE URLS (
    ID BIGSERIAL PRIMARY KEY,
    SHORTCODE VARCHAR(10) UNIQUE NOT NULL,
    ORIGINALURL TEXT NOT NULL,
    USERID BIGINT REFERENCES USERS(ID),
    CREATEDAT TIMESTAMP DEFAULT NOW(),
    EXPIRESAT TIMESTAMP,
    ISACTIVE BOOLEAN DEFAULT TRUE,
    PASSWORDHASH VARCHAR(255)
);

-- Click Events Table
CREATE TABLE CLICKEVENTS (
    ID BIGSERIAL PRIMARY KEY,
    SHORTCODE VARCHAR(10) NOT NULL,
    CLICKEDAT TIMESTAMP DEFAULT NOW(),
    IPADDRESS VARCHAR(45),
    COUNTRY VARCHAR(100),
    DEVICETYPE VARCHAR(50),
    BROWSER VARCHAR(100),
    REFERER VARCHAR(500)
);

-- URL Preference Table (for storing user strategy preferences)
-- Supports global defaults (USERID = NULL) and user-specific preferences
CREATE TABLE URL_PREFERENCE (
    ID BIGSERIAL PRIMARY KEY,
    USERID BIGINT REFERENCES USERS(ID),
    STRATEGY VARCHAR(20) NOT NULL, -- CUSTOM, RANDOM, USER_PREFERENCE
    PRIORITY_ORDER INTEGER NOT NULL,
    IS_ENABLED BOOLEAN DEFAULT TRUE,
    CONFIG_JSON TEXT,
    CREATEDAT TIMESTAMP DEFAULT NOW(),
    UPDATEDAT TIMESTAMP,
    UNIQUE(USERID, STRATEGY)
);

-- Insert global default preferences
INSERT INTO URL_PREFERENCE (USERID, STRATEGY, PRIORITY_ORDER, IS_ENABLED) VALUES
(NULL, 'CUSTOM', 1, true),
(NULL, 'RANDOM', 2, true),
(NULL, 'USER_PREFERENCE', 3, false);
