-- Schema v1: Initial database schema for URL Shortener application

-- Users table
CREATE TABLE IF NOT EXISTS USERS (
    ID BIGSERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- URL table for storing shortened URLs
CREATE TABLE IF NOT EXISTS URL (
    ID BIGSERIAL PRIMARY KEY,
    SHORTCODE VARCHAR(20) NOT NULL UNIQUE,
    ORIGINALURL TEXT NOT NULL,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USERID BIGINT,
    ISACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    EXPIRESAT TIMESTAMP,
    CONSTRAINT FK_URL_USER FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE SET NULL
);

-- Click events table for tracking URL clicks
CREATE TABLE IF NOT EXISTS CLICK_EVENT (
    ID BIGSERIAL PRIMARY KEY,
    URLID BIGINT NOT NULL,
    CLICKEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    IPADDRESS VARCHAR(45),
    USERAGENT VARCHAR(255),
    CONSTRAINT FK_CLICK_URL FOREIGN KEY (URLID) REFERENCES URL(ID) ON DELETE CASCADE
);

-- Short code configuration table
CREATE TABLE IF NOT EXISTS SHORT_CODE_CONFIG (
    ID BIGSERIAL PRIMARY KEY,
    CODE_LENGTH INTEGER NOT NULL DEFAULT 8,
    CHARSET VARCHAR(100) NOT NULL DEFAULT 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',
    ISACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- URL preference table for user-specific code generation strategies
CREATE TABLE IF NOT EXISTS URL_PREFERENCE (
    ID BIGSERIAL PRIMARY KEY,
    USERID BIGINT,
    STRATEGY VARCHAR(50) NOT NULL,
    PRIORITY_ORDER INTEGER NOT NULL,
    IS_ENABLED BOOLEAN NOT NULL DEFAULT TRUE,
    CONFIG_JSON TEXT,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP,
    CONSTRAINT FK_PREFERENCE_USER FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Code pool table for pre-generated short codes
CREATE TABLE IF NOT EXISTS CODE_POOL (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(20) NOT NULL UNIQUE,
    IS_USED BOOLEAN NOT NULL DEFAULT FALSE,
    ASSIGNED_USERID BIGINT,
    CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Insert default short code configuration
INSERT INTO SHORT_CODE_CONFIG (CODE_LENGTH, CHARSET, ISACTIVE)
VALUES (8, 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789', TRUE)
ON CONFLICT DO NOTHING;

-- Insert default URL preferences (global defaults)
INSERT INTO URL_PREFERENCE (USERID, STRATEGY, PRIORITY_ORDER, IS_ENABLED)
VALUES 
    (NULL, 'RANDOM', 1, TRUE),
    (NULL, 'CUSTOM', 2, TRUE),
    (NULL, 'USER_PREFERENCE', 3, TRUE)
ON CONFLICT DO NOTHING;
