-- Schema v2: Add performance indexes for expiry checking

-- Index for finding active URLs by short code
CREATE INDEX IF NOT EXISTS IDX_URL_SHORTCODE_ACTIVE ON URL(SHORTCODE) WHERE ISACTIVE = TRUE;

-- Index for finding active URLs by user
CREATE INDEX IF NOT EXISTS IDX_URL_USER_ACTIVE ON URL(USERID) WHERE ISACTIVE = TRUE;

-- Index for efficient expiry checking
CREATE INDEX IF NOT EXISTS IDX_URL_EXPIRES_AT ON URL(EXPIRESAT) WHERE EXPIRESAT IS NOT NULL;

-- Index for click event lookups by URL
CREATE INDEX IF NOT EXISTS IDX_CLICK_EVENT_URL ON CLICK_EVENT(URLID);

-- Index for click event timestamps
CREATE INDEX IF NOT EXISTS IDX_CLICK_EVENT_TIMESTAMP ON CLICK_EVENT(CLICKEDAT);

-- Index for code pool - finding available codes
CREATE INDEX IF NOT EXISTS IDX_CODE_POOL_AVAILABLE ON CODE_POOL(IS_USED) WHERE IS_USED = FALSE;

-- Index for code pool - finding by code string
CREATE INDEX IF NOT EXISTS IDX_CODE_POOL_CODE ON CODE_POOL(CODE);

-- Index for URL preference lookups
CREATE INDEX IF NOT EXISTS IDX_URL_PREFERENCE_USER ON URL_PREFERENCE(USERID);

-- Index for URL preference ordering
CREATE INDEX IF NOT EXISTS IDX_URL_PREFERENCE_ORDER ON URL_PREFERENCE(PRIORITY_ORDER);
