-- V1: Initial Database Schema
-- Creates the core tables for the URL Shortener application

-- Users Table
CREATE TABLE IF NOT EXISTS USERS (
    ID BIGSERIAL PRIMARY KEY,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW()
);

-- Urls Table (shortened URLs)
CREATE TABLE IF NOT EXISTS URLS (
    ID BIGSERIAL PRIMARY KEY,
    SHORTCODE VARCHAR(10) UNIQUE NOT NULL,
    ORIGINALURL TEXT NOT NULL,
    USERID BIGINT REFERENCES USERS(ID),
    CREATEDAT TIMESTAMP DEFAULT NOW(),
    EXPIRESAT TIMESTAMP,
    ISACTIVE BOOLEAN DEFAULT TRUE,
    PASSWORDHASH VARCHAR(255)
);

-- Click Events Table (for tracking URL clicks)
CREATE TABLE IF NOT EXISTS CLICKEVENTS (
    ID BIGSERIAL PRIMARY KEY,
    SHORTCODE VARCHAR(10) NOT NULL,
    CLICKEDAT TIMESTAMP DEFAULT NOW(),
    IPADDRESS VARCHAR(45),
    COUNTRY VARCHAR(100),
    DEVICETYPE VARCHAR(50),
    BROWSER VARCHAR(100),
    REFERER VARCHAR(500)
);

-- ShortCodes Table (for centralized shortcode management)
CREATE TABLE IF NOT EXISTS SHORTCODES (
    ID BIGSERIAL PRIMARY KEY,
    CODE VARCHAR(10) UNIQUE NOT NULL,
    STRATEGY VARCHAR(20) DEFAULT 'RANDOM',
    USERID BIGINT REFERENCES USERS(ID),
    PREFERENCE_ORDER INTEGER,
    ISACTIVE BOOLEAN DEFAULT TRUE,
    CREATEDAT TIMESTAMP DEFAULT NOW(),
    UPDATEDAT TIMESTAMP
);

-- URL Preference Table (for storing user strategy preferences)
CREATE TABLE IF NOT EXISTS URL_PREFERENCE (
    ID BIGSERIAL PRIMARY KEY,
    USERID BIGINT REFERENCES USERS(ID),
    STRATEGY VARCHAR(20) NOT NULL,
    PRIORITY_ORDER INTEGER NOT NULL,
    IS_ENABLED BOOLEAN DEFAULT TRUE,
    CONFIG_JSON TEXT,
    CREATEDAT TIMESTAMP DEFAULT NOW(),
    UPDATEDAT TIMESTAMP,
    UNIQUE(USERID, STRATEGY)
);

-- Insert global default preferences
INSERT INTO URL_PREFERENCE (USERID, STRATEGY, PRIORITY_ORDER, IS_ENABLED) VALUES
(NULL, 'CUSTOM', 1, true),
(NULL, 'RANDOM', 2, true),
(NULL, 'USER_PREFERENCE', 3, false)
ON CONFLICT DO NOTHING;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_urls_shortcode ON URLS(SHORTCODE);
CREATE INDEX IF NOT EXISTS idx_urls_userid ON URLS(USERID);
CREATE INDEX IF NOT EXISTS idx_urls_isactive ON URLS(ISACTIVE);
CREATE INDEX IF NOT EXISTS idx_urls_userid_isactive ON URLS(USERID, ISACTIVE);
CREATE INDEX IF NOT EXISTS idx_shortcodes_code ON SHORTCODES(CODE);
CREATE INDEX IF NOT EXISTS idx_clickevents_shortcode ON CLICKEVENTS(SHORTCODE);
CREATE INDEX IF NOT EXISTS idx_clickevents_clickedat ON CLICKEVENTS(CLICKEDAT);
